lab_10/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^check_email/$', views.check_email, name='check_email')
]

lab_11/urls.py
from django.urls import re_path
from .views import index

urlpatterns = [
    re_path(r'^$', index),
]

lab_6/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^add_status/$', views.add_status, name='add_status'),
    re_path(r'^challenge/$', views.challenge, name='challenge')
]

lab_8/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
]

lab_9/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^endpoint/$', views.endpoint, name='endpoint')
]

pepew/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView
from lab_11.views import logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('lab_8.urls', 'lab_8'), namespace='lab_8')),
    path('lab_6/', include(('lab_6.urls', 'lab_6'), namespace='lab_6')),
    path('lab_9/', include(('lab_9.urls', 'lab_9'), namespace='lab_9')),
    path('lab_10/', include(('lab_10.urls', 'lab_10'), namespace='lab_10')),
    path('lab_11/', include(('lab_11.urls', 'lab_11'), namespace='lab_11')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('login/', LoginView.as_view(template_name='lab_11/login.html'), name='login'),
    path('logout/', logout, name='logout'),
]

lab_10/models.py
from django.db import models

# Create your models here.
class Subscriber(models.Model):
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=128)
    password = models.CharField(max_length=64)

    def __str__(self):
        return self.email
    

lab_11/models.py
from django.db import models

lab_6/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Status(models.Model):
    date = models.DateTimeField(default=timezone.now)
    content = models.TextField(max_length=300)

lab_8/models.py
from django.db import models

# Create your models here.

lab_9/models.py
from django.db import models

# Create your models here.

lab_10/forms.py
from django import forms
from .models import Subscriber


class Subscriber_Form(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = '__all__'
        widgets = {
            'email': forms.TextInput(attrs={'class': 'emailClass'}),
            'name': forms.TextInput(attrs={'class': 'nameClass'}),
            'password': forms.PasswordInput(attrs={'class': 'passwordClass'}),
        }

lab_11/forms.py
from django.shortcuts import redirect, HttpResponseRedirect
from django.contrib.auth import logout
from django.contrib.auth.models import User
from .models import Profile
from django import forms

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio','location','birth_date')

lab_6/forms.py
from django import forms
from .models import Status


class Status_Form(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['content']
        labels = {
            'content': '',
        }
        widgets = {
            'content': forms.Textarea(attrs={'cols':70, 'rows':10, 'id': 'content'}),
        }

lab_10/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import Subscriber_Form
from .models import Subscriber
from django.core.validators import validate_email

# Create your views here.
def index(request):
    form = Subscriber_Form(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)

    else:
        form = Subscriber_Form()
        return render(request, 'lab_10/index.html', {'form': form})

@csrf_exempt
def check_email(request):
    email = request.POST['email']
    num_user = Subscriber.objects.filter(email=email).count()
    try:
        validate_email(email)
        valid_email = True
    except:
        valid_email = False
    response = {
        'valid_email': valid_email,
        'subscribed': num_user == 1,
    }
    return JsonResponse(response)

lab_11/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as logout_user

def index(request):
    return render(request, 'lab_11/index.html')

def logout(request):
    logout_user(request)
    return redirect('/lab_11/')

lab_6/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Status
from .forms import Status_Form

# Create your views here.
def index(request):
    response = {}
    response['status_list'] = Status.objects.all()
    response['status_form'] = Status_Form
    return render(request, 'index.html', response)

def add_status(request):
    response = {}
    form = Status_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['content'] = request.POST['content']
        status = Status(content=response['content'])
        status.save()

    return HttpResponseRedirect('/')

def challenge(request):
    return render(request, 'challenge.html')

lab_8/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'landing_page.html')

lab_9/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import requests
import json

# Create your views here.
def index(request):
    return render(request, 'lab_9/index.html')

def endpoint(request):
    response = requests.get('https://www.googleapis.com/books/v1/volumes?q=quilting')
    return JsonResponse(response.json())

lab_10/templates/lab_10/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'lab_10/styles.css' %}">
  <script src="{% static 'lab_10/story10.js' %}"> </script>  
</head>

<body>
<div class="container">
    <div class="row text-center">
        <h1 class="mar-top-50"> SUBSCRIBE NOW </h1>
        <form novalidate id="subscribe-form" class="mar-top-50">
            {% csrf_token %}
            {% for i in form %}
                <h4>{{i.label_tag}} {{i}}</h4>
            {% endfor %}
            <button class="btn btn-primary disabled" id="submit-subscribe">
                Submit
            </button>
        </form>
    </div>
</div>

<div class="modal fade" id="subscribed-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="subscribed-modal-title">Subscribe Berhasil</h5>
      </div>
      <div class="modal-body">
            Anda telah berhasil berlangganan
      </div>
      <div class="modal-footer">
        <a role="button" href="/lab_10/" class="btn secondary">
            Kembali ke profil
        </a>
      </div>
    </div>
  </div>
</div>

</body>

</html>

lab_11/templates/lab_11/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock title %}</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
	{% block head %}
	{% endblock head %}
</head>
<body>
	<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
		<div class="container">
				<a class="navbar-brand" href="/lab_11/">Story 11</a>
		</div>  
	</nav>
    <div class="container">
	    {% block content %}	
	    {% endblock content %}
    </div>
</body>
</html>

lab_11/templates/lab_11/index.html
{% extends "lab_11/base.html" %}
{% load static %}

{% block title %}Story 11{% endblock %}

{% block head %}
	<link rel="stylesheet" href="{% static 'lab_9/styles.css' %}">
	<script src="{% static 'lab_9/story9.js' %}"> </script>  
{% endblock %}

{% block content %}
	{% if user.is_authenticated %}
        <p class="display-4">Hello, {{ user.first_name }} {{ user.last_name}}</p>
		<a class="lead" href="{% url 'logout' %}">Log out</a>
		<div class="panel text-center">
			<div>
				<img src="/static/lab_9/star-cute.svg" class="big-star">
				<span id="favorite-count">0</span>
				<img src="/static/lab_9/star-cute.svg" class="big-star">
			</div>
		</div>
		<div class="panel p-5">
			<h1 class="text-center">KOLEKSI BUKU</h1>
			<table class="table table-light table-striped">
				<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Cover</th>
					<th scope="col">Judul</th>
					<th scope="col">Penulis</th>
					<th scope="col">Penerbit</th>
					<th scope="col">Favorit</th>
				</tr>
				</thead>
				<tbody id="content">
				</tbody>
			</table>
		</div>

	{% else %}
		<a class="lead" href="{% url 'login' %}">Log in</a>
	{% endif %}
{% endblock content %}

lab_11/templates/lab_11/login.html
{% extends "lab_11/base.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}

  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
   <br>
  <p><strong>-- OR --</strong></p>
  <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>

{% endblock %}

lab_6/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title%} {% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href={% static 'lab_6/styles.css' %}>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
</head>


<div class="content">
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <a class="navbar-brand" href="#">Logo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span></button>
  <div class="collapse navbar-collapse" id="collapsibleNavId">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="/lab_6/">Status</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/lab_6/challenge/">Challenge</a>
      </li>
    </ul>
  </div>
</nav>

{% block content %}
{% endblock %}

</div>
</html>

lab_6/templates/challenge.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block content %}
<body>
<div class="container-fluid text-center">    
  <div id="home">
    <div class="row content">
      <div class="col-sm-2 sidenav">
        <img 
        id="my-image"
        src="https://media.licdn.com/dms/image/C5103AQH1_dFTPONWoQ/profile-displayphoto-shrink_200_200/0?e=1540425600&v=beta&t=566E-H3xkXFZUwyXgOn2o58IbAmoP9TXYI_H8mxNA98">
      </div>
      <div class="col-sm-10 text-left" id="description"> 
        <h2>This Challenge Page is Actually a Profile Page</h2>
        <p class="short-paragraph">Currently majoring Computer Science at Universitas Indonesia.
        <br>Interested at data science and competitive programming.
        <br>A student and a lifetime learner.
        </p>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid text-center">
  <div id="resume">
    <p class="section-title">RESUME</p>  
    <div class="row content">
      <div class="col-sm-4 sidenav">
        <div class="card">
          <img class="card-img-top" data-src="holder.js/100x180/?text=Image cap">
          <div class="card-body">
            <h4 class="card-title">Education</h4>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">SD YPS Singkole <br>(2005-2011)</li>
            <li class="list-group-item">SMP Pribadi Bandung <br>(2011-2014)</li>
            <li class="list-group-item">SMA Pribadi Bandung <br>(2014-2017)</li>
            <li class="list-group-item">Universitas Indonesia <br>(2017-now)</li>
          </ul>
        </div>
      </div>  
      <div class="col-sm-4 sidenav">
        <div class="card">
          <img class="card-img-top" data-src="holder.js/100x180/?text=Image cap">
          <div class="card-body">
            <h4 class="card-title">Work Experience</h4>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Software Engineer Internship at GDP Labs <br>
              (Jun 2017-Aug 2017)</li>
            <li class="list-group-item">Discrete Mathematics 1 Teaching Assistant <br>
              (Sep 2017-now)</li>
          </ul>
        </div>
      </div>
      <div class="col-sm-4 sidenav">
        <div class="card">
          <img class="card-img-top" data-src="holder.js/100x180/?text=Image cap">
          <div class="card-body">
            <h4 class="card-title">Projects</h4>
          </div>
          <ul class="list-group list-group-flush">
          </ul>
        </div>
      </div> 
    </div>
  </div>
</div>
</body>
{% endblock %}

lab_6/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Update Status{% endblock %}
{% block content %}
<body>
    <div class="container-fluid text-center">
        <h1 style="margin-top:25px">Hello, apa kabar?</h1>
        <p class="section-title">UPDATE STATUS</p>
        <section name="form">
            <form method="POST" action="{% url 'lab_6:add_status' %}">
                {% csrf_token %}
                {{status_form}}
                <br/>
                <button type="submit" class="btn btn-default" id="submit-button">Submit</button>
            </form>
        </section>
    </div>

    <div class="container-fluid text-center">
        <p class="section-title">LIHAT STATUS</p>
        {% for i in status_list %}
            <p>Waktu : {{ i.date }}</p>
            <p>Status : {{ i.content }}</p>
        {% endfor %}
    </div>
</body>
{% endblock %}

lab_8/templates/landing_page.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'lab_8/styles.css' %}">
  <script src="{% static 'lab_8/story8.js' %}"> </script>  
</head>

<body onload="move()">

  <div id="progress" class="col-md-12">
    <div id="bar"></div>
  </div>

  <div id="content" class="col-md-12 hidden">
    <h3> Nama : Muhammad Ridho Ananda </h3>
    <button class="font-black" onclick="changeTheme()"> Change Theme </button>
    <div class="panel-title font-black mar-top-50">
      <div class="panel panel-default">
        <div onclick="accordion('1')" class="panel-heading">
          Aktivitas
        </div>
        <div id="panel-1" class="panel-body hidden">
          - Belajar <br>
          - Bernafas <br>
        </div>
        <div onclick="accordion('2')" class="panel-heading">
          Organisasi/Kepanitiaan
        </div>
        <div id="panel-2" class="panel-body hidden">
          - FUKI Fasilkom UI <br>
          - RISTEK Fasilkom UI <br>
          - COMPFEST X <br>
        </div>
        <div onclick="accordion('3')" class="panel-heading">
          Prestasi
        </div>
        <div id="panel-3" class="panel-body hidden">
          - Lomba Pemrograman Gemastik 10 <br>
          - Senior Competitive Programming Contest COMPFEST 9 <br>
          - Junior Competitive Programming Contest COMPFEST 8 <br>
        </div>
      </div>
    </div>
  </div>
</body>

lab_9/templates/lab_9/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'lab_9/styles.css' %}">
  <script src="{% static 'lab_9/story9.js' %}"> </script>  
</head>

<body>
<div class="container">
    <div class="panel text-center">
        <div>
            <img src="/static/lab_9/star-cute.svg" class="big-star">
            <span id="favorite-count">0</span>
            <img src="/static/lab_9/star-cute.svg" class="big-star">
        </div>
    </div>
    <div class="panel p-5">
        <h1 class="text-center">KOLEKSI BUKU</h1>
        <table class="table table-light table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Cover</th>
                <th scope="col">Judul</th>
                <th scope="col">Penulis</th>
                <th scope="col">Penerbit</th>
                <th scope="col">Favorit</th>
            </tr>
            </thead>
            <tbody id="content">
            </tbody>
        </table>
    </div>
</div>
</body>